// Référentiel officiel classes → matières + coefficients (système Togo).
// Utilisé par l'onboarding ("Charger les matières de ma classe") et,
// demain, par l'assistant anonyme. Les totaux affichés sur les bulletins
// ne servent pas au calcul : l'app pondère avec chaque coef individuel.
export const MATIERES_PAR_CLASSE = {
  "6ème": [
    { nom: "Français", coef: 1, icon: "menu_book" },
    { nom: "Mathématiques", coef: 1, icon: "calculate" },
    { nom: "Physique-Chimie", coef: 1, icon: "science" },
    { nom: "Histoire-Géo", coef: 1, icon: "public" },
    { nom: "Anglais", coef: 1, icon: "language" },
    { nom: "ECM", coef: 1, icon: "gavel" },
    { nom: "SVT", coef: 1, icon: "biotech" },
    { nom: "EPS", coef: 1, icon: "sports_soccer" },
    { nom: "Dictée-Question", coef: 1, icon: "edit_note" },
  ],
  "5ème": [
    { nom: "Français", coef: 1, icon: "menu_book" },
    { nom: "Mathématiques", coef: 1, icon: "calculate" },
    { nom: "Physique-Chimie", coef: 1, icon: "science" },
    { nom: "Histoire-Géo", coef: 1, icon: "public" },
    { nom: "Anglais", coef: 1, icon: "language" },
    { nom: "ECM", coef: 1, icon: "gavel" },
    { nom: "SVT", coef: 1, icon: "biotech" },
    { nom: "EPS", coef: 1, icon: "sports_soccer" },
    { nom: "Dictée-Question", coef: 1, icon: "edit_note" },
  ],
  "4ème": [
    { nom: "Dictée-Question", coef: 2, icon: "edit_note" },
    { nom: "Français", coef: 2, icon: "menu_book" },
    { nom: "Anglais", coef: 2, icon: "language" },
    { nom: "Histoire-Géo", coef: 2, icon: "public" },
    { nom: "SVT", coef: 2, icon: "biotech" },
    { nom: "Mathématiques", coef: 2, icon: "calculate" },
    { nom: "Physique-Chimie", coef: 2, icon: "science" },
    { nom: "ECM", coef: 2, icon: "gavel" },
    { nom: "EPS", coef: 1, icon: "sports_soccer" },
  ],
  "3ème": [
    { nom: "Dictée-Question", coef: 2, icon: "edit_note" },
    { nom: "Français", coef: 2, icon: "menu_book" },
    { nom: "Anglais", coef: 2, icon: "language" },
    { nom: "Histoire-Géo", coef: 2, icon: "public" },
    { nom: "SVT", coef: 2, icon: "biotech" },
    { nom: "Mathématiques", coef: 2, icon: "calculate" },
    { nom: "Physique-Chimie", coef: 2, icon: "science" },
    { nom: "ECM", coef: 2, icon: "gavel" },
    { nom: "EPS", coef: 1, icon: "sports_soccer" },
  ],
  "Seconde A": [
    { nom: "Philosophie", coef: 2, icon: "psychology" },
    { nom: "Français", coef: 4, icon: "menu_book" },
    { nom: "Histoire-Géo", coef: 3, icon: "public" },
    { nom: "ECM", coef: 2, icon: "gavel" },
    { nom: "Anglais", coef: 3, icon: "language" },
    { nom: "LV2 (All/Esp)", coef: 2, icon: "translate" },
    { nom: "Mathématiques", coef: 2, icon: "calculate" },
    { nom: "Physique-Chimie", coef: 1, icon: "science" },
    { nom: "SVT", coef: 1, icon: "biotech" },
    { nom: "EPS", coef: 1, icon: "sports_soccer" },
  ],
  "Seconde C/D": [
    { nom: "Philosophie", coef: 1, icon: "psychology" },
    { nom: "Français", coef: 2, icon: "menu_book" },
    { nom: "Histoire-Géo", coef: 2, icon: "public" },
    { nom: "ECM", coef: 2, icon: "gavel" },
    { nom: "Anglais", coef: 2, icon: "language" },
    { nom: "Mathématiques", coef: 4, icon: "calculate" },
    { nom: "Physique-Chimie", coef: 3, icon: "science" },
    { nom: "SVT", coef: 3, icon: "biotech" },
    { nom: "EPS", coef: 1, icon: "sports_soccer" },
  ],
  "Première A": [
    { nom: "Français", coef: 4, icon: "menu_book" },
    { nom: "Histoire-Géo", coef: 3, icon: "public" },
    { nom: "ECM", coef: 2, icon: "gavel" },
    { nom: "Anglais", coef: 3, icon: "language" },
    { nom: "LV2 (All/Esp)", coef: 2, icon: "translate" },
    { nom: "Mathématiques", coef: 2, icon: "calculate" },
    { nom: "Physique-Chimie", coef: 1, icon: "science" },
    { nom: "SVT", coef: 1, icon: "biotech" },
    { nom: "EPS", coef: 1, icon: "sports_soccer" },
  ],
  "Première C": [
    { nom: "Français", coef: 2, icon: "menu_book" },
    { nom: "Histoire-Géo", coef: 2, icon: "public" },
    { nom: "ECM", coef: 2, icon: "gavel" },
    { nom: "Anglais", coef: 2, icon: "language" },
    { nom: "Mathématiques", coef: 5, icon: "calculate" },
    { nom: "Physique-Chimie", coef: 4, icon: "science" },
    { nom: "SVT", coef: 2, icon: "biotech" },
    { nom: "EPS", coef: 1, icon: "sports_soccer" },
  ],
  "Première D": [
    { nom: "Français", coef: 2, icon: "menu_book" },
    { nom: "Histoire-Géo", coef: 2, icon: "public" },
    { nom: "ECM", coef: 2, icon: "gavel" },
    { nom: "Anglais", coef: 2, icon: "language" },
    { nom: "Mathématiques", coef: 3, icon: "calculate" },
    { nom: "Physique-Chimie", coef: 3, icon: "science" },
    { nom: "SVT", coef: 4, icon: "biotech" },
    { nom: "EPS", coef: 1, icon: "sports_soccer" },
  ],
  "Terminale A": [
    { nom: "Philosophie", coef: 4, icon: "psychology" },
    { nom: "Français", coef: 3, icon: "menu_book" },
    { nom: "Histoire-Géo", coef: 3, icon: "public" },
    { nom: "ECM", coef: 2, icon: "gavel" },
    { nom: "Anglais", coef: 3, icon: "language" },
    { nom: "LV2 (All/Esp)", coef: 2, icon: "translate" },
    { nom: "Mathématiques", coef: 2, icon: "calculate" },
    { nom: "Physique-Chimie", coef: 1, icon: "science" },
    { nom: "SVT", coef: 1, icon: "biotech" },
    { nom: "EPS", coef: 1, icon: "sports_soccer" },
  ],
  "Terminale C": [
    { nom: "Philosophie", coef: 2, icon: "psychology" },
    { nom: "Français", coef: 2, icon: "menu_book" },
    { nom: "Histoire-Géo", coef: 2, icon: "public" },
    { nom: "ECM", coef: 2, icon: "gavel" },
    { nom: "Anglais", coef: 2, icon: "language" },
    { nom: "Mathématiques", coef: 5, icon: "calculate" },
    { nom: "Physique-Chimie", coef: 4, icon: "science" },
    { nom: "SVT", coef: 2, icon: "biotech" },
    { nom: "EPS", coef: 1, icon: "sports_soccer" },
  ],
  "Terminale D": [
    { nom: "Philosophie", coef: 2, icon: "psychology" },
    { nom: "Français", coef: 2, icon: "menu_book" },
    { nom: "Histoire-Géo", coef: 2, icon: "public" },
    { nom: "ECM", coef: 2, icon: "gavel" },
    { nom: "Anglais", coef: 2, icon: "language" },
    { nom: "Mathématiques", coef: 3, icon: "calculate" },
    { nom: "Physique-Chimie", coef: 3, icon: "science" },
    { nom: "SVT", coef: 4, icon: "biotech" },
    { nom: "EPS", coef: 1, icon: "sports_soccer" },
  ],
};

export function matieresDe(classe) {
  return MATIERES_PAR_CLASSE[classe] || null;
}
